CREATE TABLE "SARTS01D"."TRANSACTION_DATA" (
	  "ETID" VARCHAR(8) NOT NULL
	, "DATA" VARCHAR(2000) FOR BIT DATA NOT NULL
	, CONSTRAINT "TRANSACTION_DATA_PK" PRIMARY KEY ("ETID")
);

-- CREATE GLOBAL TEMPORARY TABLE "SARTS01D"."RETAIN_SETS" (
-- 	  "SETNAME" VARCHAR(32) NOT NULL
-- 	, "ISN"	DECIMAL(10, 0) NOT NULL
-- ) ;
CREATE TABLE "SARTS01D"."F0001" (
  "ISN" DECIMAL(10, 0) NOT NULL
, "F_AA" VARGRAPHIC(17) DEFAULT ' '
, "D_AA" VARCHAR(17) FOR BIT DATA
, "F_CB" VARGRAPHIC(9)
, "D_CB" VARCHAR(9) FOR BIT DATA
, "F_CE" GRAPHIC(1)
, "F_CF" GRAPHIC(1)
, "F_CG" GRAPHIC(1)
, "F_CJ" VARGRAPHIC(19)
, "F_CK" GRAPHIC(2)
, "F_CM" VARGRAPHIC(5)
, "F_CN" GRAPHIC(4)
, "F_CO" GRAPHIC(4)
, "F_CP" DECIMAL(1, 0)
, "F_CQ" DECIMAL(1, 0)
, "F_DA" VARGRAPHIC(22) DEFAULT ' '
, "D_DA" VARCHAR(22) FOR BIT DATA
, "F_EA" VARGRAPHIC(17)
, "F_EB" DECIMAL(8, 0)
, "F_FB" GRAPHIC(1)
, "F_FC" DECIMAL(2, 0)
, "F_FD" DECIMAL(8, 0)
, "F_FE" GRAPHIC(2)
, "F_FG" DECIMAL(1, 0)
, "F_GB" VARGRAPHIC(24)
, "F_GC" VARGRAPHIC(11)
, "F_GD" GRAPHIC(2)
, "F_GE" DECIMAL(1, 0)
, "F_HB" GRAPHIC(2)
, "F_HC" VARGRAPHIC(8)
, "F_HD" GRAPHIC(4)
, "F_HE" DECIMAL(4, 0)
, "F_HF" GRAPHIC(3)
, "F_HG" DECIMAL(4, 2)
, "F_HH" GRAPHIC(4)
, "F_HI" DECIMAL(4, 0)
, "F_HJ" GRAPHIC(1)
, "F_HK" VARGRAPHIC(22)
, "F_HL" DECIMAL(2, 0)
, "F_HM" GRAPHIC(1)
, "F_HN" VARGRAPHIC(6)
, "F_HO" DECIMAL(10, 2)
, "F_HP" DECIMAL(8, 0)
, "F_HQ" DECIMAL(8, 2)
, "F_HR" VARGRAPHIC(6)
, "F_HT" DECIMAL(6, 0)
, "F_HU" DECIMAL(1, 0)
, "F_IB" DECIMAL(1, 0)
, "F_IC" DECIMAL(1, 0)
, "F_ID" DECIMAL(1, 0)
, "F_IE" DECIMAL(1, 0)
, "F_IF" DECIMAL(1, 0)
, "F_IG" DECIMAL(1, 0)
, "F_IH" DECIMAL(1, 0)
, "F_II" DECIMAL(1, 0)
, "F_IJ" DECIMAL(1, 0)
, "F_IK" DECIMAL(1, 0)
, "F_IL" DECIMAL(1, 0)
, "F_IM" DECIMAL(1, 0)
, "F_IN" DECIMAL(1, 0)
, "F_IO" DECIMAL(1, 0)
, "F_IP" DECIMAL(1, 0)
, "F_IQ" DECIMAL(1, 0)
, "F_IR" DECIMAL(1, 0)
, "F_IT" DECIMAL(1, 0)
, "F_IU" DECIMAL(1, 0)
, "F_IV" DECIMAL(1, 0)
, "F_IW" DECIMAL(1, 0)
, "F_KA" DECIMAL(8, 2)
, "F_KB" GRAPHIC(2)
, "F_KC" DECIMAL(8, 0)
, "F_LA" VARGRAPHIC(9)
, "F_LB" DECIMAL(8, 0)
, "F_MC" VARGRAPHIC(19)
, "F_MD" GRAPHIC(2)
, "F_MF" VARGRAPHIC(5)
, "F_MG" GRAPHIC(4)
, "F_ND" GRAPHIC(2)
, "F_OA" GRAPHIC(1)
, "F_OB" DECIMAL(3, 0)
, "F_OC" DECIMAL(2, 0)
, "F_OD" DECIMAL(1, 0)
, "F_OE" DECIMAL(1, 0)
, "F_PA" DECIMAL(8, 0)
, "F_PB" DECIMAL(1, 0)
, "F_PC" DECIMAL(1, 0) DEFAULT 0
, "F_PD" GRAPHIC(1) DEFAULT ' '
, "F_PE" GRAPHIC(1) DEFAULT ' '
, "F_QA" GRAPHIC(1) DEFAULT ' '
, "F_QB" GRAPHIC(1) DEFAULT ' '
, "F_QC" GRAPHIC(3)
, "F_QD" GRAPHIC(3)
, "F_QE" DECIMAL(8, 0)
, "F_QF" VARGRAPHIC(30)
, "F_QG" VARGRAPHIC(30)
, "F_QH" DECIMAL(1, 0)
, "F_QI" DECIMAL(1, 0)
, "F_QJ" DECIMAL(1, 0)
, "F_RA" VARGRAPHIC(17)
, "D_RA" VARCHAR(17) FOR BIT DATA
, "F_RB" VARGRAPHIC(22)
, "D_RB" VARCHAR(22) FOR BIT DATA
, "F_RC" GRAPHIC(2)
, "F_RD" DECIMAL(8, 0)
, "F_RE" VARGRAPHIC(6)
, "F_RF" DECIMAL(8, 0)
, "F_RG" DECIMAL(8, 0)
, "F_RH" DECIMAL(8, 0)
, "F_RI" GRAPHIC(2)
, "F_RJ" DECIMAL(8, 0)
, "F_RK" GRAPHIC(2)
, "F_RL" DECIMAL(8, 0)
, "D_ZA" VARCHAR(19) FOR BIT DATA
, CONSTRAINT "F0001_PK" PRIMARY KEY ("ISN")
);
CREATE INDEX "SARTS01D"."F0001_D_AA" ON "SARTS01D"."F0001" ("D_AA" ASC, "ISN" ASC);
CREATE INDEX "SARTS01D"."F0001_D_CB" ON "SARTS01D"."F0001" ("D_CB" ASC, "ISN" ASC);
CREATE INDEX "SARTS01D"."F0001_D_DA" ON "SARTS01D"."F0001" ("D_DA" ASC, "ISN" ASC);
CREATE INDEX "SARTS01D"."F0001_D_RA" ON "SARTS01D"."F0001" ("D_RA" ASC, "ISN" ASC);
CREATE INDEX "SARTS01D"."F0001_D_RB" ON "SARTS01D"."F0001" ("D_RB" ASC, "ISN" ASC);
CREATE INDEX "SARTS01D"."F0001_D_ZA" ON "SARTS01D"."F0001" ("D_ZA" ASC, "ISN" ASC);

CREATE TABLE "SARTS01D"."F0001_PE_BA" (
  "ISN" DECIMAL(10, 0) NOT NULL
, "PE_IDX" DECIMAL(5, 0) NOT NULL
, "F_BB" VARGRAPHIC(7)
, "F_BC" DECIMAL(4, 0)
, "F_BD" DECIMAL(2, 0)
, "F_BE" DECIMAL(1, 0)
, CONSTRAINT "F0001_PE_BA_PK" PRIMARY KEY ("ISN", "PE_IDX")
, CONSTRAINT "F0001_PE_BA_FK_ISN" FOREIGN KEY ("ISN") REFERENCES "SARTS01D"."F0001" ("ISN") ON DELETE CASCADE
);

CREATE TABLE "SARTS01D"."F0001_MU_CC" (
  "ISN" DECIMAL(10, 0) NOT NULL
, "MU_IDX" DECIMAL(5, 0) NOT NULL
, "F_CC" VARGRAPHIC(30)
, CONSTRAINT "F0001_MU_CC_PK" PRIMARY KEY ("ISN", "MU_IDX")
, CONSTRAINT "F0001_MU_CC_FK_ISN" FOREIGN KEY ("ISN") REFERENCES "SARTS01D"."F0001" ("ISN") ON DELETE CASCADE
);

CREATE TABLE "SARTS01D"."F0001_MU_CI" (
  "ISN" DECIMAL(10, 0) NOT NULL
, "MU_IDX" DECIMAL(5, 0) NOT NULL
, "F_CI" VARGRAPHIC(30)
, CONSTRAINT "F0001_MU_CI_PK" PRIMARY KEY ("ISN", "MU_IDX")
, CONSTRAINT "F0001_MU_CI_FK_ISN" FOREIGN KEY ("ISN") REFERENCES "SARTS01D"."F0001" ("ISN") ON DELETE CASCADE
);

CREATE TABLE "SARTS01D"."F0001_MU_MB" (
  "ISN" DECIMAL(10, 0) NOT NULL
, "MU_IDX" DECIMAL(5, 0) NOT NULL
, "F_MB" VARGRAPHIC(30)
, CONSTRAINT "F0001_MU_MB_PK" PRIMARY KEY ("ISN", "MU_IDX")
, CONSTRAINT "F0001_MU_MB_FK_ISN" FOREIGN KEY ("ISN") REFERENCES "SARTS01D"."F0001" ("ISN") ON DELETE CASCADE
);